### PR TITLE
AerospikeTemplate: rework count method, fixes #102

### LINKED ISSUE #102: count method fails with exception if set is not present
```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
    at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
    at java.lang.String.substring(String.java:1874) ~[?:?]
    at org.springframework.data.aerospike.core.AerospikeTemplate.count(AerospikeTemplate.java:442) ~[spring-data-aerospike-2.4.0.RELEASE.jar:?]
```

### PR DESCRIPTION
**Pull request by Aloren**

### CODE REVIEW

**Review by tdanylchuk — APPROVED** [review]

File: src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java [hunk 1]
```diff
@@ -430,21 +431,21 @@ public AerospikeClient getAerospikeClient() {
...
-					infoString.indexOf("=") + 1, infoString.indexOf(":"));
-			n_objects = Integer.parseInt(n_objectsString);
-		}
+		try {
+			Node[] nodes = client.getNodes();
+
+			int replicationFactor = getReplicationFactor(nodes);
 
-		return (nodeCount > 1) ? n_objects / replicationCount : n_objects;
+			long totalObjects = Arrays.stream(nodes)
```
Comment (tdanylchuk) [inline src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java:441]: @rbotzer can we have `count` function integrated inside AerospikeClient, I believe it would be a proper place for it there.
